export const SCREENS = {
  HUB: 'hub',
  EVENTS: 'events',
  EVENT: 'event',
  EVENT_PHOTOS: 'event-photos',
  EVENT_ATTENDEES: 'event-attendees',
  EVENT_SALES: 'event-sales',
  SALES: 'sales',
  SALE_DETAIL: 'sale-detail',
  AUDIENCE: 'audience',
  CONTROLLERS: 'controllers',
  FINANCE: 'finance',
  KYC: 'kyc',
  DOCUMENTS: 'documents',
  PROFILE_EDIT: 'profile-edit',
  PROFILE_LOGO: 'profile-logo',
  SOCIALS: 'socials',
  ORG_QR: 'org-qr',
};
